### ISSUE TITLE
Problemas al importar modules

### ISSUE THREAD

**Issue by 62fixolab** [migueltoro/adda2018#3]
Cuando realicé el *fetch* de la última versión de su repositorio todo empezó a darme problemas en Eclipse, incluidas las primeras prácticas.
He realizado algunas pruebas llegando a las siguientes conclusiones:

- El *commit* actual 89c845eb97696e01e96a511ae6cc9d470236c6cf del 2-3-19 tiene problemas a la hora de importar los *modules*.
<img width="1067" alt="actual 2-3-19 con problemas" src="https://user-images.githubusercontent.com/12599130/53775558-5412bd00-3ef3-11e9-960f-31805255891d.png">

- Sin embargo he usado el *commit* 85053782e465c73624971e6b0191213b287a9ef5 del 12/12/18 y todo va perfecto.
<img width="1068" alt="pasado 12-12-18 todo perfecto" src="https://user-images.githubusercontent.com/12599130/53775556-5412bd00-3ef3-11e9-8388-29b3f9a9bead.png">

- Esto soluciona los problemas con **ParteComún** y con **DatosCompartidos**, sin embargo el *commit*  del 12-12-18 no contiene las librerías para poder usar los **Grafos**, por tanto no me soluciona el problema, ya que estos siguen dando error de modules con el *commit* actual 2-3-19.

Supongo que todo el mundo estará teniendo problemas al usar el repositorio, ya que incluso importando manualmente sin usar *Git Repositories* de Eclipse funcionan los *modules*.

**Comment by mrf1989** [comment]
Hola, yo he pasado por una situación similar. A día de hoy tengo la última versión del repositorio y todo funciona bien.

Te recomiendo que no uses en tu proyecto el module-info.java, no lo crees. Simplemente configura el Build Path del proyecto para que requiera y reconozca los proyectos de los que dependerá.

Además, en caso de que estés con Mac, tendrás que configurar la librería LPSolve para poder utilizarla de igual manera, tanto en proyectos del repositorio como en tus propios proyectos.

**Comment by 62fixolab** [comment]
Ya he solucionado el problema a la hora de usar proyectos con Grafos y @mrf1989 tiene toda la razón. Adjunto imágenes del proceso e instrucciones para que todo el que tenga el problema pueda solucionarlo:
1.  Eliminar *module-info.java* si es un proyecto que ya tienes creado, si es un nuevo proyecto simplemente al crearlo selecciona *Don't Create*.

2. Copiar las librerías que se encuentran en la carpeta *lib* del proyecto **EjemplosDeGrafos** a una carpeta que vamos a crear en nuestro proyecto llamada por ejemplo *lib*.
<img width="351" alt="captura de pantalla 2019-03-05 a las 16 02 25" src="https://user-images.githubusercontent.com/12599130/53814542-15671c00-3f60-11e9-9f98-49b0db6b5ebe.png">

3. Hacer click derecho sobre nuestro proyecto e ir a *Build Path > Configure Builth Path...* Hacemos click en *Classpath* y luego en *Add* para añadir los de los que depende tu proyecto La estructura tiene que ser similar a la siguiente:
<img width="741" alt="captura de pantalla 2019-03-05 a las 15 57 22" src="https://user-images.githubusercontent.com/12599130/53814239-8bb74e80-3f5f-11e9-9913-aae05627e418.png">

4. Añadimos las librerías haciendo click en *Classpath* y luego en *Add JARs...*.
<img width="741" alt="captura de pantalla 2019-03-05 a las 15 57 40" src="https://user-images.githubusercontent.com/12599130/53814232-85c16d80-3f5f-11e9-8ab3-4e1ca7f178d2.png">

Y ya tendríamos funcionando los proyectos del 2º Cuatrimestre relacionados con Grafos.

**Todo esto es aplicable a los proyectos del 1º Cuatrimestre, la única diferencia es que solo tendríamos realizar los pasos 1 y 3, ya que estos proyectos no contenían librerías**
